apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploymentapp
  namespace: test-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
selector:
  matchLabels:
    app: maven
template: 
  name: maven-web-app
  labels: 
    app: maven
  spec:
    containers:
    - name: maven-container
      image: jagadeeeshdockerhub/maven-web-application:TAG
      ports:
      - containerPort: 8080
---
apiVersion: v1 
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: test-ns
spec: 
  type: NodePort
  selector: 
    app: maven
  ports:
  - port: 80
    targetPort: 8080
